### PR TITLE
adding changes for white_value deprecation

### LINKED ISSUE #5: 2022.6 breaking changes
https://www.home-assistant.io/blog/2022/06/01/release-20226/

the 2022.6 release seems to add some breaking changes on mqtt an template ( white_value)

does someone know how to update the config to make it compatible with the 2022.6 ?

### PR DESCRIPTION
**Pull request by Dilergore**
resolves #5

### CODE REVIEW

**Comment by Dilergore** [comment]
@thehookup - If you are still monitoring this repo, I think it would help a lot of people if you could merge this. This documentation I think helped a lot of us to set up Shelly RGBW in the past, including me. There is still a gap in HA, none of the available integrations (Offical / ShellyForHASS) are compatible with Shelly RGBW controlled RGBW strips.

**Comment by martinkoe09** [comment]
Tested your amendments and they do work, except a warning about the missing unique id (probably not related to your code). I will hopefully work that out.

**Comment by Dilergore** [comment]
@thehookup - Could you please merge this?

**Comment by thehookup** [comment]
Merged.

**Comment by Dilergore** [comment]
Thanks :)

**Pull request merged**
